# Generated by Django 4.2.14 on 2024-08-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='https://royalspice.nl/wp-content/uploads/2021/11/Chicken-Tikka-Balti.webp', null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=450, null=True)),
                ('non_vegetarian', models.BooleanField(default=False, null=True)),
                ('description', models.TextField(blank=True, max_length=4500, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protien', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
