# Generated by Django 4.2.14 on 2024-08-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ingredients_added',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ingredients'),
        ),
    ]
