# Generated by Django 4.2.14 on 2024-08-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fooditem_ingredients_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients_added',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ingredients'),
        ),
    ]
