# Generated by Django 4.2.14 on 2024-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_ingredients_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
