# Generated by Django 4.2.14 on 2024-08-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_ingredients_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredients',
            new_name='name',
        ),
    ]
