# Generated by Django 4.2.14 on 2024-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_ingredients_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default='salt', max_length=200),
        ),
    ]
