# Generated by Django 4.2.14 on 2024-08-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_ingredients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
