# Generated by Django 4.2.14 on 2024-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_fooditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='imageUrl',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
