# Generated by Django 5.0.7 on 2024-08-03 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_fooditem_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('imageUrl', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, default='https://royalspice.nl/wp-content/uploads/2021/11/Fernandes-Blauw.webp', null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=450, null=True)),
                ('description', models.TextField(blank=True, max_length=4500, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protien', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('sat_fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ingredients_added', models.ManyToManyField(blank=True, null=True, to='base.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('imageUrl', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, default='https://royalspice.nl/wp-content/uploads/2021/11/Fernandes-Blauw.webp', null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=450, null=True)),
                ('description', models.TextField(blank=True, max_length=4500, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protien', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('sat_fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ingredients_added', models.ManyToManyField(blank=True, null=True, to='base.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('imageUrl', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, default='https://royalspice.nl/wp-content/uploads/2021/11/Fernandes-Blauw.webp', null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=450, null=True)),
                ('description', models.TextField(blank=True, max_length=4500, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protien', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('sat_fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ingredients_added', models.ManyToManyField(blank=True, null=True, to='base.ingredients')),
            ],
        ),
    ]
